language: android

sudo: false

install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.1
  - android-24

script: 
  - jdk_switcher use oraclejdk8
  - ./gradlew relinker:testReleaseUnitTest
